from functools import reduce

products = ["Sankofa Foods", "Jamestown Coffee", "Bioko Chocolate", "Blue Skies Ice Cream", "Fair Afric Chocolate",
            "Kawa Moka Coffee", "Aphro Spirit", "Mensado Bissap", "Voltic"]

prices = [30, 25, 40, 20, 20, 35, 45, 50, 35]

last_week = [2, 3, 5, 8, 4, 4, 6, 2, 9]


def calculate_total_price_average():
    total = 0
    for price in prices:
        total += price
    return format_output(total / len(prices))


def create_new_price_list():
    products_prices = {product: (prices[index] - 5) for index, product in enumerate(products)}
    return products_prices


def calculate_total_revenue():
    revenue = reduce(lambda acc_sum, curr_total: acc_sum + curr_total,
                     map(lambda price, customer_no: price * customer_no, prices, last_week))
    return format_output(revenue)


def calculate_average_daily_revenue():
    # assuming a week has 7 days
    daily_avg_revenue = float(calculate_total_revenue()) / 7
    return format_output(daily_avg_revenue)


def get_products_less_than_30():
    new_price_list = create_new_price_list()
    return [k for k, v in new_price_list.items() if v < 30]


def ask_continue():
    user_input = input('Do you want to continue? yes or no: ')
    if user_input.lower() == 'yes':
        compute()
    else:
        print('Bye!')


def format_output(no):
    return format(no, '.2f')


def compute():
    user_input = get_user_input()

    validate_input(user_input)

    if user_input == '1':
        print_separators()
        print('Total price average for all products')
        print(calculate_total_price_average())
        print_separators()
    elif user_input == '2':
        print_separators()
        print('New price list that reduces the old prices by $5')
        new_prices = create_new_price_list()
        for product, price in new_prices.items():
            print(f'{product}: ${price}')
        print_separators()
    elif user_input == '3':
        print_separators()
        print('Total revenue generated from the products')
        print(calculate_total_revenue())
        print_separators()
    elif user_input == '4':
        print_separators()
        print('Daily average revenue generated from the products')
        print(calculate_average_daily_revenue())
        print_separators()
    elif user_input == '5':
        print_separators()
        print('Products less than 30$ based on the new prices')
        filtered_products = get_products_less_than_30()
        for product in filtered_products:
            print(product)
        print_separators()

    ask_continue()


def print_separators():
    print('-' * 20)


def get_user_input():
    print('Azubi Store')
    print('1: Calculate Total price average for all products')
    print('2: Create a new price list that reduces the old prices by $5')
    print('3: Calculate the total revenue generated from the products')
    print('4: Calculate the average daily revenue generated by the products')
    print('5: Based on the new prices, which products are less than $ 30')
    user_input = input('Select choices (1,2,3,4,5): ')
    return user_input


def validate_input(user_input):
    if user_input not in ['1', '2', '3', '4', '5']:
        print('Invalid input')
        compute()


compute()
